- id: doi:10.1038/s41557-024-01463-7
  type: paper
  description: Genetically encoded bioorthogonal tryptophan decaging enables ondemand activation of over 20000 proteins in living cells.
  date: 2024-2-28
  image: images/Trp-CAGE.png
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review
  authors:
    - "**Yuchao Zhu** #"
    - "Wenlong Ding #"
    - Yulin Chen
    - Ye Shan
    - Chao Liu
    - "Xinyuan Fan *"
    - "Shixian Lin *"
    - "Peng R. Chen *"

- id:  doi:10.1038/s41586-025-09464-3
  image: images/RCE.png
  authors:
    - "Jiangle Liu #"
    - "Xueqing Yan #"
    - "Hao Wu #"
    - Ziqin Ji
    - Ye Shan
    - Xinyan Wang
    - Yunfan Ran
    - Yichen Ma
    - Caitao Li
    - "**Yuchao Zhu**"
    - Ruichu Gu
    - Han Wen
    - "Chengqi Yi *"
    - "Peng R. Chen *"

- id:  doi:10.1038/s41586-025-09165-x
  image: images/RCE.png
  authors:
    - "Jiangle Liu #"
    - "Xueqing Yan #"
    - "Hao Wu #"
    - Ziqin Ji
    - Ye Shan
    - Xinyan Wang
    - Yunfan Ran
    - Yichen Ma
    - Caitao Li
    - "**Yuchao Zhu**"
    - Ruichu Gu
    - Han Wen
    - "Chengqi Yi *"
    - "Peng R. Chen *"

- id: doi:10.1002/cjoc.202400876
  image: images/BCR.png
  authors:
    - "**Yuchao Zhu**"
    - Feng Lin
    - Ziqi Liu
    - Xin Wang
    - Shubing Wang
    - "Xinyuan Fan *"
    - "Peng R. Chen *"

- id: doi:10.1002/anie.202007187
  image: images/Diol.png

- id: doi:10.1038/s41929-019-0398-0
  image: images/DMSO.png
  authors:
    - Song Song
    - Xinyao Li
    - Jialiang Wei
    - Weijin Wang
    - Yiqun Zhang
    - Lingsheng Ai
    - "**Yuchao Zhu**"
    - Xiaomeng Shi
    - Xiaohui Zhang
    - "Ning Jiao *"

- id: doi:10.1002/anie.201903690
  image: images/Bencong.png
  authors:
    - Bencong Zhu
    - Tao Shen
    - Xiaoqiang Huang
    - "**Yuchao Zhu**"
    - Song Song
    - "Ning Jiao *"

- id: doi:10.1002/anie.201900947
  image: images/Qixue.png
  authors:
    - Qixue Qin
    - Xiao Luo
    - Jialiang Wei
    - "**Yuchao Zhu**"
    - Xiaojin Wen
    - Song Song
    - "Ning Jiao *"

- id: doi:10.1038/s41557-018-0156-y
  image: images/Jianzhong.png
  authors:
    - Jianzhong Liu
    - Xu Qiu
    - Xiaoqiang Huang
    - Xiao Luo
    - Cheng Zhang
    - Jialiang Wei
    - Jun Pan
    - Yujie Liang
    - "**Yuchao Zhu**"
    - Qixue Qin
    - Song Song
    - "Ning Jiao *"

- id: doi:10.1038/s41467-018-05014-w
  image: images/Mono-ol.png
  authors:
    - "**Yuchao Zhu**"
    - Kaimeng Huang
    - Jun Pan
    - Xu Qiu
    - Xiao Luo
    - Qixue Qin
    - Jialiang Wei
    - Xiaojin Wen
    - Lizhi Zhang
    - "Ning Jiao *"

- id: doi:10.1002/chem.201605476
  image: images/CEJ.png
  authors:
    - Jianzhong Liu
    - Kai Wu
    - Tao Shen
    - Yujie Liang
    - Miancheng Zou
    - "**Yuchao Zhu**"
    - Xinwei Li
    - Xinyao Li
    - "Ning Jiao *"

- id: doi:10.1021/acscatal.6b02074
  image: images/Oxime.png
  authors:
    - "**Yuchao Zhu**"
    - Xiaojin Wen
    - "Song Song *"
    - "Ning Jiao *"

- id: doi:10.1021/acs.orglett.5b02155
  image: images/Azidation.png
  authors:
    - "**Yuchao Zhu**"
    - Xinyao Li
    - Xiaoyang Wang
    - Xiaoqiang Huang
    - Tao Shen
    - Yiqun Zhang
    - Xiang Sun
    - Miancheng Zou
    - "Song Song *"
    - "Ning Jiao *"
  
- id: doi:10.1021/jacs.5b02347
  image: images/Sunxiang.png
   authors:
    - Xiang Sun
    - Xinyao Li
    - Song Song
    - "**Yuchao Zhu**"
    - Yu-Feng Liang
    - "Ning Jiao *"
